apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easytrade-ephemerals
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: ArctiqDynatraceDemo
        repo: easytrade
        tokenRef:
            secretName: github-token
            key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: "easytrade-preview-pr-{{.number}}"
      labels:
        image: "credit-card-order-service"
        tag: "pr.{{.number}}-sha.{{.head_short_sha}}"
      annotations:
        kargo.akuity.io/authorized-stage: "easytrade:preview"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/ArctiqDynatraceDemo/gitops
        targetRevision: HEAD
        path: easytrade/dev
        kustomize:
          images:
            - "ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service:pr.{{.number}}-sha.{{.head_short_sha}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'easytrade-preview-pr-{{.number}}'
      
      
