resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml
  - ../applications/

patches:
  - path: argo-cm.yml
  - path: argo-rbac-cm.yml
