resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  # - https://github.com/cert-manager/cert-manager/releases/download/v3.3.0/cert-manager.yaml
  - ../applications/

patches:
  - path: argo-cm.yml
  - path: argo-rbac-cm.yml
  # - patch: rollout-extension.yml
  - patch: notifications.yml
