apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: easytrade-uat

resources:
- ../base

images:
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/accountservice"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/aggregator-service"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/broker-service"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/calculationservice"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/db"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/engine"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/feature-flag-service"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/frontend"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/frontendreverseproxy"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/loadgen"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/loginservice"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/manager"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/offerservice"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/pricing-service"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/problem-operator"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/rabbitmq"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"
  - name: "ghcr.io/arctiqdynatracedemo/easytrade/third-party-service"
    newTag: "338da683d94cdbf25d9c021c5162173d17659fdc"