apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easytrade-qa
resources:
- ../base
images:
- name: ghcr.io/arctiqdynatracedemo/easytrade/accountservice
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/aggregator-service
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/broker-service
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/calculationservice
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/db
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/engine
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/feature-flag-service
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/frontend
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/frontendreverseproxy
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/loadgen
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/loginservice
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/manager
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/offerservice
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/pricing-service
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/problem-operator
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/rabbitmq
  newTag: 1.0.1-dev-sha.6b0908e4
- name: ghcr.io/arctiqdynatracedemo/easytrade/third-party-service
  newTag: 1.0.1-dev-sha.6b0908e4
