apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-argocd-external-link-to-services
spec:
  rules:
    - name: annotate-services
      match:
        resources:
          kinds:
            - Service
      exclude:
        resources:
          namespaces:
            - tailscale
            - kube-system
            - kyverno
            - argocd
      preconditions:
        all:
        - key: "{{request.operation}}"
          operator: NotEquals
          value: DELETE
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              link.argocd.argoproj.io/external-link: http://"{{(request.object.metadata.name || request.object.metadata.generateName) }}-{{request.namespace}}.tail0ae91.ts.net:{{(request.object.spec.ports[0].port || "80") }}"
              tailscale.com/expose: "true"