apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-argocd-external-link-to-services
spec:
  rules:
    - name: annotate-services
      match:
        resources:
          kinds:
            - Service
      preconditions:
        all:
        - key: "{{request.operation}}"
          operator: NotEquals
          value: DELETE
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              link.argocd.argoproj.io/external-link: "{{request.object.metadata.name}}-{{request.namespace}}"
              tailscale.com/expose: "true"